version: '3.8'

services:
  app:
    build: .
    container_name: eccom-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - $MS_PORT:8080
